CREATE TABLE "user_type" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_type" char
);

CREATE TABLE "user_authorization" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_fid" integer,
  "user_name" varchar(30),
  "user_password" varchar(30)
);

ALTER TABLE "user_authorization" ADD FOREIGN KEY ("user_fid") REFERENCES "user_type" ("user_id");
